---
- name: Gather facts from FlashSystem and store in inventory
  hosts: ibm_flashsystems
  gather_facts: false
  become: false
  vars_files:
    - vars/authentication.yml
  tasks:
    - name: gather facts using ibm_svc_info
      ibm.spectrum_virtualize.ibm_svc_info:
        clustername: "{{ clustername }}"
        gather_subset: array
        token: "{{ api_token }}"
      register: results

    - name: Print out results.array
      ansible.builtin.debug:
        msg: "{{ results.Array }}"

    - name: use ansible set_fact to define array_results using results.Array
      ansible.builtin.set_fact:
        array_results: "{{ results.Array }}"