---
- name: Generate API token for FlashSystem
  hosts: v7g3flash
  gather_facts: false 
  
  vars_files:
    - vars/authentication.yml
  tasks:
    - name: use ibm_spectrum_virtualize.ibm_svc_auth to generate API token
      ibm.storage_virtualize.ibm_svc_auth:
        clustername: "{{clustername}}"
        #domain: "{{domain}}"
        username: "{{username}}"
        password: "{{ _password_ }}"
      register: result
      no_log: true

    - name: preserve result using set_stat 
      ansible.builtin.set_stats:
        data:
          api_token: "{{result.token}}"
      no_log: true
    
 