---
- name: Generate API token for FlashSystem
  hosts: ibm-flashsystems
  gather_facts: false 
  # collections:
  #   - ibm.spectrum_virtualize
  vars_files:
    - vars/authentication.yml
  tasks:
    - name: use ibm_spectrum_virtualize.ibm_svc_auth to generate API token
      ibm.spectrum_virtualize.ibm_svc_auth:
        clustername: "{{clustername}}"
        #domain: "{{domain}}"
        username: "{{username}}"
        password: "{{ _password_ }}"
      register: result

    - name: preserve result using set_stat 
      ansible.builtin.set_stats:
        data:
          api_token: "{{result.token}}"
    
 