---
- name: Append additional volumes to vars/addvolume.csv
  hosts: localhost
  gather_facts: false
  become: true
  vars_files:
    - vars/authentication.yml
  vars:
    ansible_connection: local
    
  #   start_var: 2
  #   end_var: 10
  #   countby_var: 2
  #   vol_base: demo_vol
  #   pool: Pool01
  #   size: 1024
  #   thin: true
  #   unit: gb 
  #   os: aix
  #   hostname: bpicaix04
  #   host_fqdn: bpicaix04.bpic.mainline.com
  #   esx_datastore_name: ''
  #   esx_datastore_type : ''
    


  tasks:
  - name: gather facts using ibm_svc_info
    ibm.storage_virtualize.ibm_svc_info:
      clustername: "{{ clustername }}"
      gather_subset: pool
      username: ansible 
      password: M@inline1700
      # token: "{{ api_token }}"
    register: svc_results
#    no_log: true

  - name: create array list of results.list name for use in jinja2 template
    create_survey_info:
      info_results: "{{ svc_results.Pool }}"
      info_value: name
    register: pool_names


  # - name: Gather datastore info from vmware vcenter
  #   community.vmware.vmware_datastore_info:
  #     hostname: "{{ vcenter_hostname }}"
  #     schema: summary
  #     username: "{{ vcenter_username }}"
  #     password: "{{ vcenter_password }}"
  #     datacenter: Datacenter
  #     validate_certs: false
  #   register: datastore_info
  
  # - name: create array list of datastore.list name for use in jinja2 template
  #   create_survey_lists:
  #     info_results: "{{ datastore_info.datastores }}"
  #     info_value: name
  #   register: datastore_names

  - name: Create volume_spec.json by using ansible.builtin.template and /templates/dyn_survey_vol.j2
    ansible.builtin.template:
      src: dyn_survey_vol.j2
      dest: /tmp/dyn_survey_vol.json
      mode: '0644'
    register: spec_results

  - name: Update FlashSystem Volume Survey
    ansible.controller.job_template:
      name: IBM_FlashSystem_Self_Service_Update_CSV
      survey_enabled: true
      survey_spec: "{{ lookup('file','/tmp/dyn_survey_vol.json') }}"
      validate_certs: no
      inventory: ibm_storage_and_hosts
      playbook: flashsystem_self_service.yml
      project: "FlashSystem Management"
        # controller_password: M@inline1700
        # controller_username: ian.wright
        # controller_host: ansible.bpic.mainline.com
      controller_config_file: /etc/ansible/ansible.cfg
 
 
  # - name: Create dyn_survey_vol.json by using ansible.builtin.template and /templates/dyn_survey_vol.j2
  #   ansible.builtin.template:
  #     src: dyn_survey_vol.j2j2
  #     dest: /tmp/dyn_survey_vol.json
  #     mode: '0644'
  #   register: spec_results

  # # - name: Update ESX DataStore Survey
  # #   ansible.controller.job_template:
  # #     name: "esx_update"
  # #     survey_enabled: true
  # #     survey_spec: "{{ lookup('file', 'self_service_survey_spec_esx.json') }}"
    # when: os == 'esx'

  
