---
- name: Append additional volumes to vars/addvolume.csv
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - vars/authentication.yml
  # vars:
  #   start_var: 2
  #   end_var: 10
  #   countby_var: 2
  #   vol_base: demo_vol
  #   pool: Pool01
  #   size: 1024
  #   thin: true
  #   unit: gb 
  #   os: aix
  #   hostname: bpicaix04
  #   host_fqdn: bpicaix04.bpic.mainline.com
  #   esx_datastore_name: ''
  #   esx_datastore_type : ''


  tasks:
  - name: Create a variable with a list of values
    create_volume_name:
      vol_base_name: "{{ vol_base }}"
      vol_sequence_begin: "{{ start_var }}"
      vol_sequence_end: "{{ end_var }}"
      vol_sequence_increment: "{{ countby_var }}"
    register: name_list
  
  - name: Print out name_list.vol_names
    ansible.builtin.debug:
      msg: "{{ name_list.vol_names }}"

 
  - name: Fail if volume already exists
    ansible.builtin.fail:
      msg: "Volume Name {{ item }} already exists. Please correct and try again"
    when: "{{ lookup('csvfile', item + ' file=vars/addvolume.csv col=0 delimiter=,') }}"
    loop: "{{ name_list.vol_names }}"
    
  - name: Add vars to vars/addvolume.csv to add new volumes when { item } is not present in list added_volumes
    ansible.builtin.lineinfile:
      path: vars/addvolume.csv
      line: "{{item }},{{ pool }},{{ size }},{{ thin }},{{ unit }},{{ os }},{{ hostname }},{{host_fqdn }},{{esx_datastore_name }},{{ esx_datastore_type }}"
    loop: "{{ name_list.vol_names }}"