---
- name: Gather facts from FlashSystem and store in inventory
  hosts: v7g3flash
  gather_facts: false
  become: true
  collections:
    - ibm.storage_virtualize
  vars_files:
    - vars/authentication.yml
 
  tasks:
    - name: gather facts using ibm_svc_info
      ibm.storage_virtualize.ibm_svc_info:
        clustername: "{{ clustername }}"
        gather_subset: all
        username: ansible
        password: M@inline1700
      #  token: "{{ api_token }}"
      register: results
      # delegate_facts: true
      # delegate_to: v7g3flash

    - name: Print out results.array
      ansible.builtin.debug:
        msg: "{{ results.Array }}"

    - name: create directory for /etc/ansible/facts.d/ if it doesn't exist
      ansible.builtin.file:
        path: /etc/ansible/facts.d
        recurse: true
        state: directory
        
    - name: import registered variable results.Array into set_fact
      ansible.builtin.set_fact:
        array_details: "{{ results.Array[0] }}"
      delegate_facts: true
      delegate_to: v7g3flash

    - name: write array_results to /etc/ansible/facts.d/
      ansible.builtin.copy:
        content: "{{ results.Array [0] }}"
        dest: /etc/ansible/facts.d/array_results.fact