---
- name: Create or validate hosts
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - vars/authentication.yml
 
  tasks:
   
  - name: Read the csv file containing volume information
    community.general.read_csv:
      path: vars/addvolume.csv
    register: added_volumes

  - name: Use ibm.storage_virtualize.ibm_svc_manage_volume with a loop to create new volumes from CSV file
    # added_volumes.list is needed from registered variable
    ibm.storage_virtualize.ibm_svc_manage_volume:
      clustername: "{{ clustername }}"
      log_path: '/tmp/svc_create_volume.debug'
      state: present
      name: "{{ item.name }}"
      size: "{{ item.size }}"
      unit: "{{ item.unit }}"
      thin: "{{ item.thin }}"
      pool: "{{ item.pool }}"
      validate_certs: false
      token: "{{ api_token }}"
      # username: 
      # password: 
    loop: "{{ added_volumes.list}}"

  - name: Map volumes to hosts based on information from csv file
    # again, uses added_volumes.list as the source of the information
    ibm.storage_virtualize.ibm_svc_vol_map:
      clustername: "{{ clustername }}"
      host: "{{ hostname }}"
      state: present
      volname: "{{ item.name }}"
      log_path: '/tmp/map_volume_to_host.debug'
      token: "{{ api_token }}"
      # username:
      # password: 
    loop: "{{ added_volumes.list }}"
  
  - name: preserve API token with set_stats
    # preserving api_token for any additional playbooks in workflow
    ansible.builtin.set_stats:
      data:
        api_token: "{{ api_token }}"
  
  