---
- name: Remove Volumes listed in csv file
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - vars/authentication.yml
 
  tasks:
   
  - name: Read the csv file containing volume information
    community.general.read_csv:
      path: vars/addvolume.csv
    register: added_volumes

  - name: Use ibm.storage_virtualize.ibm_svc_manage_volume with a loop to remove volumes based on CSV file
    # added_volumes.list is needed from registered variable
    ibm.storage_virtualize.ibm_svc_manage_volume:
      clustername: "{{ clustername }}"
      log_path: '/tmp/svc_create_volume.debug'
      state: absent
      name: "{{ item.name }}"
      size: "{{ item.size }}"
      unit: "{{ item.unit }}"
      thin: "{{ item.thin }}"
      pool: "{{ item.pool }}"
      validate_certs: false
      token: "{{ api_token }}"
      # username: 
      # password: 
    loop: "{{ added_volumes.list}}"
  
  
  
  