- name: Configuration work for newly created VMs including copying SSH keys for Ansible access and registering with Satellite
  hosts: flashsystem_attached_vms
  gather_facts: true
  become: true
  vars_files:
    - vars/authentication.yml
  
  tasks:
    - name: use authorized_key to copy lab_vm_key to host 
      ansible.posix.authorized_key:
        user: ansible
        state: present
        key: "{{ lab_vm_key }}"
      retries: 3
      delay: 10

    - name: set sudo to do passwordless root for user ansible
      ansible.builtin.copy:
        content: ansible ALL=(ALL) NOPASSWD:ALL
        dest: /etc/sudoers.d/ansible
        validate: /usr/sbin/visudo -csf %s
        owner: root
        group: root
        mode: '0644'


    - name: Make sure that /etc/sysconfig/network has line HOSTNAME="{{ HOSTNAME + '.' + domain }}"
      ansible.builtin.lineinfile:
        path: /etc/sysconfig/network
        line: HOSTNAME="{{ ansible_hostname + '.' + domain }}"
        regexp: ^HOSTNAME=
        state: present

    - name: change hostname in /etc/hosts to ansible_hostname and domain
      ansible.builtin.hostname:
        name: "{{ ansible_hostname + '.' + domain }}"
        use: systemd

    - name: Restart NetworkManager.service with ansible.builtin.systemd_service
      ansible.builtin.systemd_service:
        name: NetworkManager.service
        state: restarted

    - name: register with Red Hat Satellite server at satellite_server using activation key 
      community.general.redhat_subscription:
        state: present
        activationkey: "{{ satellite_activation_key }}"
        server_hostname: "{{ satellite_hostname }}"
        org_id: "{{ satellite_org }}"
        force_register: true
        server_insecure: true