---
- name: Build self-service template and survey based on current information
  hosts: localhost
  gather_facts: false
  become: true
  vars_files:
    - vars/authentication.yml
  # vars:
  #   ansible_connection: local
    # configuration_type: 'Create volumes'

  tasks:
    - name: gather facts using ibm_svc_info
      ibm.storage_virtualize.ibm_svc_info:
        clustername: "{{ clustername }}"
        gather_subset: pool
        token: "{{ api_token }}"
      register: svc_results
  #    no_log: true

    - name: create array list of results.list name for use in jinja2 template
      create_survey_info:
        info_results: "{{ svc_results.Pool }}"
        info_value: name
      register: pool_names
    
    - when: ("{{ configuration_type }} == 'Map unmapped volumes'")
      block:
        - name: Gather svc_info for volumes that haven't been mapped
          ibm.storage_virtualize.ibm_svc_info:
            clustername: "{{ clustername }}"
            gather_subset: hostvdiskmap
            username: ansible 
            password: M@inline1700
          register: mapped_hosts

        - name: Get vdisk_name from mapped_hosts
          create_survey_info:
            info_results: "{{ mapped_hosts.HostVdiskMap }}"
            info_value: vdisk_name
          register: mapped_volumes

        - name: Get svc_info of all volumes
          ibm.storage_virtualize.ibm_svc_info:
            clustername: "{{ clustername }}"
            gather_subset: vol
            username: 
            password: 
          register: all_volumes

        - name: get names of all volumes
          create_survey_info:
            info_results: "{{ all_volumes.Volume }}" 
            info_value: volume_name 
          register: all_volume_names

        - name: create a new list by removing an item when vdisk_name = name
          reduce_lists:
            list_to_remove: "{{ mapped_volumes.survey_info }}"
            main_list: "{{ all_volume_names.survey_info }}"
          register: unmapped_volumes

    - when: ("{{ configuration_type }} == 'Create and map volumes'") or ("{{ configuration_type }} == 'Map unmapped volumes'")
      block: 
      - name: Gather svc_info for volumes that haven't been mapped
        ibm.storage_virtualize.ibm_svc_info:
          clustername: "{{ clustername }}"
          gather_subset: host
          username: 
          password: 
        register: all_hosts

      - name: Get vdisk_name from mapped_hosts
        create_survey_info:
          info_results: "{{ all_hosts.Host }}"
          info_value: name
        register: host_list

      - name: Create volume_spec.json by using ansible.builtin.template and /templates/dyn_survey_vol.j2
        ansible.builtin.template:
          src: dyn_survey_vol.j2
          dest: /tmp/dyn_survey_vol.json
          # dest: /home/ansible/playbooks/flashsystem_setup/templates/dyn_survey_vol.json
          mode: '0644'
        register: spec_results

      - name: Update FlashSystem Volume Survey
        ansible.controller.job_template:
          name: IBM_FlashSystem_Self_Service_Update_CSV
          # ask_variables_on_launch: true
          execution_environment: ee-ibm-flashsystem
          survey_enabled: true
          survey_spec: "{{ lookup('file','/tmp/dyn_survey_vol.json') }}"
          validate_certs: no
          credentials:
            - 'ansible server credential'
            - 'ansible_vault_credential'
          inventory: ibm_storage_and_hosts
          playbook: flashsystem_self_service.yml
          project: 'FlashSystem Management'
          controller_password: 
          controller_username: 
          controller_host: ansible.bpic.mainline.com
          controller_config_file: /etc/ansible/ansible.cfg
          extra_vars:
            configuration_type: "{{ configuration_type }}"
