---
- name: Gather facts from FlashSystem and store in inventory
  hosts: ibm_flashsystems
  gather_facts: false
  become: false
  vars_files:
    - vars/authentication.yml
  tasks:
    - name: gather facts using ibm_svc_info
      ibm.spectrum_virtualize.ibm_svc_info:
        clustername: "{{ clustername }}"
        gather_subset: array
        token: "{{ api_token }}"
      register: results

    - name: Print out results.array
      ansible.builtin.debug:
        msg: "{{ results.Array }}"

    - name: create /etc/ansible/facts.d/ directory if it doesn't exist
      ansible.builtin.file:
        path: /etc/ansible/facts.d/
        state: directory
        recurse: true
    
    - name: copy results.Array to /etc/ansible/facts.d/
      ansible.builtin.copy:
        src: "{{ results.Array }}"
        dest: /etc/ansible/facts.d/
        #owner: root
        #group: root
        #mode: 493
        #backup: true