---
- name: add volumes to FlashSystem
  hosts: localhost
  gather_facts: false
  become: true
  vars_files:
    - vars/authentication.yml
      
  tasks:
  - name: read the csv file
    community.general.read_csv:
      path: vars/addvolumes.csv
      key: name
    register: volumes
 
   
  - name: create volumes using svc_manage_volume
    ibm.storage_virtualize.ibm_svc_manage_volume:
      clustername: "{{ clustername }}"
      name: "{{ volumes.dict.name }}"
      pool: "{{ volumes.dict.pool }}"
      size: "{{ volumes.dict.size }}"
      thin: "{{ volumes.dict.thin }}"
      unit: "{{ volumes.dict.unit }}"
      validate_certs: "{{ volumes.validate_certs }}" 
      state: present
      log_path: /tmp/flashsystem/svc_create_volume.debug     
      token: "{{ api_token }}"
    loop: "{{ volumes.dict }}"
    loop_control:
      loop_var: "{{ volumes.dict.name }}"
    
    # - name: make sure that host exists using ibm.storage_virtualize.ibm_svc_host
    #   ibm.storage_virtualize.ibm_svc_host:
    #     clustername: "{{ clustername }}"
    #     name: "{{ volumes.hostname }}"
    #     iscsiname: "{{ volumes.isciname }}"
    #     token: "{{ api_token }}"
    #     state: present
    #     protocol: scsi
    #     type: generic
    #     validate_certs: "{{ volumes.validate_certs }}"
    #     log_path: /tmp/flashsystem/validate_host.debug
      
    # - name: map volume to host
    #   ibm.storage_virtualize.ibm_svc_vol_map:
    #     clustername: "{{ clustername }}"
    #     host: "{{ volumes.hostname }}"
    #     state: present
    #     volname: "{{ volumes.name }}"
    #     log_path: "{{ /tmp/flashsystem/map_volume_to_host.debug }}"
    #     token: "{{ api_token }}"
    
    # loop: volumes.dict
    # loop_control:
    #   loop_var: volumes

  
