---
- name: Gather facts from FlashSystem and store in inventory
  hosts: localhost
  gather_facts: false
  become: true
  collections:
    - ibm.spectrum_virtualize
  vars_files:
    - vars/authentication.yml
  vars:
    array_str: |
      { name}

  tasks:
    - name: gather facts using ibm_svc_info
      ibm.spectrum_virtualize.ibm_svc_info:
        clustername: "{{ clustername }}"
        gather_subset: array
        username: ansible
        password: M@inline1700
      #  token: "{{ api_token }}"
      register: results

    - name: Print out results.array
      ansible.builtin.debug:
        msg: "{{ results.Array }}"

    # - name: use ansible set_fact to define array_results using results.Array
    #   ansible.builtin.set_fact:
    #     array_results: "{{ results.Array }}"
    #   delegate_facts: true
    #   delegate_to: v7g3flash

    - name: create directory for /etc/ansible/facts.d/ if it doesn't exist
      ansible.builtin.file:
        path: /etc/ansible/facts.d
        recurse: true
        state: directory
        
    - name: import registered variable results.Array into set_fact
      ansible.builtin.set_fact:
        array_details: "{{ results.Array[0] }}"

    # - name: write array_results to /etc/ansible/facts.d/
    #   ansible.builtin.copy:
    #     content: "{{ results.Array | items2dict }}"
    #     dest: /etc/ansible/facts.d/array_results.fact

    -