- name: Configuration work for newly created VMs including copying SSH keys for Ansible access and registering with Satellite
  hosts: flashsystem_attached_vms
  gather_facts: true
  become: true
  vars_files:
    - vars/authentication.yml
  
  tasks:
    - name: use authorized_key to copy lab_vm_key to host 
      ansible.posix.authorized_key:
        user: ansible
        state: present
        key: "{{ lab_vm_key }}"

    - name: Make sure that /etc/sysconfig/network has line HOSTNAME="{{ HOSTNAME }}"."{{ domain }}"
      ansible.builtin.lineinfile:
        path: /etc/sysconfig/network
        line: HOSTNAME="{{ ansible_facts['ansible_hostname'] }}"."{{ domain }}"
        regexp: ^HOSTNAME=
        state: present

    - name: register with Red Hat Satellite server at satellite_server using activation key 
      community.general.redhat_subscription:
        state: present
        activationkey: "{{ satellite_activation_key }}"
        server_hostname: "{{ satellite_hostname }}"
        org_id: "{{ satellite_org }}"
        force_register: true
        server_insecure: true