---
- name: Gather facts from FlashSystem and store in inventory
  hosts: v7g3flash
  gather_facts: false
  become: true
  vars_files:
    - vars/authentication.yml
  tasks:
    - name: gather facts using ibm_svc_info
      ibm.spectrum_virtualize.ibm_svc_info:
        clustername: "{{ clustername }}"
        gather_subset: array
        token: "{{ api_token }}"
      register: results

    - name: Print out results.array
      ansible.builtin.debug:
        msg: "{{ results.Array }}"

    # - name: use ansible set_fact to define array_results using results.Array
    #   ansible.builtin.set_fact:
    #     array_results: "{{ results.Array }}"

    - name: create directory for /etc/ansible/facts.d/ if it doesn't exist
      ansible.builtin.file:
        path: /etc/ansible/facts.d
        recurse: true
        state: directory
        

    - name: write array_results to /etc/ansible/facts.d/
      ansible.builtin.template:
        src: "{{ results.Array }}"
        dest: /etc/ansible/facts.d/array_results.fact

    - name: print the contents of the file /etc/ansible/facts.d/array_results.fact
      ansible.builtin.command: cat /etc/ansible/facts.d/array_results.fact