---
- name: Generate API token for FlashSystem
  hosts: localhost
  gather_facts: false 
  collections:
    - ibm.spectrum_virtualize
  vars_files:
    - vars/authentication.yml
  tasks:
    - name: use ibm_spectrum_virtualize.ibm_svc_auth to generate API token
      ibm.spectrum_virtualize.ibm_svc_auth:
            clustername: "{{clustername}}"
            #domain: "{{domain}}"
            username: "{{username}}"
            password: "{{ _password_ }}"
      register: result

    - name: save result as fact 
      ansible.builtin.set_fact:
        cacheable: true
        api_token: "{{result.token}}"
    
    - name: print ansible_fact api_token
      ansible.builtin.debug:
        "{{ hostvars['v7kg3flash']['api_token'] }}"