download_url: https://automationhub.bpic.mainline.com/api/galaxy/v3/plugin/ansible/content/community/collections/artifacts/community-windows-2.0.0.tar.gz
format_version: 1.0.0
name: windows
namespace: community
server: https://automationhub.bpic.mainline.com/api/galaxy/content/community/
signatures: []
version: 2.0.0
version_url: /api/galaxy/content/community/v3/plugin/ansible/content/community/collections/index/community/windows/versions/2.0.0/
