download_url: https://automationhub.bpic.mainline.com/api/galaxy/v3/plugin/ansible/content/community/collections/artifacts/ansible-windows-2.1.0.tar.gz
format_version: 1.0.0
name: windows
namespace: ansible
server: https://automationhub.bpic.mainline.com/api/galaxy/content/community/
signatures: []
version: 2.1.0
version_url: /api/galaxy/content/community/v3/plugin/ansible/content/community/collections/index/ansible/windows/versions/2.1.0/
